//#region MACROS
export const MACRO_HOME = 0;
export const MACRO_COOPERATIVA = 1;
export const MACRO_INTEGRAZIONE = 2;
export const MACRO_AFRICA = 3;
export const MACRO_INCLUSIONE = 4;
export const MACRO_COMUNITA = 5;
//#endregion

//#region MACRO POSITIONS
const MACRO_POSITIONS = new Array(6);
MACRO_POSITIONS[MACRO_HOME] = [50, 0, 190];
MACRO_POSITIONS[MACRO_COOPERATIVA] = [-150, 0, 50];
MACRO_POSITIONS[MACRO_INTEGRAZIONE] = [180, 0, 40];
MACRO_POSITIONS[MACRO_AFRICA] = [150, 0, -130];
MACRO_POSITIONS[MACRO_INCLUSIONE] = [-100, 0, -170];
MACRO_POSITIONS[MACRO_COMUNITA] = [56, 0, -292];
export { MACRO_POSITIONS };
//#endregion

//#region CAM TARGETS
const CAM_TARGETS = new Array(6);
CAM_TARGETS[MACRO_HOME] = [40, 20, 190];
CAM_TARGETS[MACRO_COOPERATIVA] = [-150, 22, 50];
CAM_TARGETS[MACRO_INTEGRAZIONE] = [180, 15, 40];
CAM_TARGETS[MACRO_AFRICA] = [150, 8, -130];
CAM_TARGETS[MACRO_INCLUSIONE] = [-100, 14, -170];
CAM_TARGETS[MACRO_COMUNITA] = [0, 0, -1];
export { CAM_TARGETS };
//#endregion

//#region CAM MINOR TARGETS
const CAM_MINOR_TARGETS = new Array(6);
CAM_MINOR_TARGETS[MACRO_HOME] = [50, 20, 190];
CAM_MINOR_TARGETS[MACRO_COOPERATIVA] = [-150, 22, 50];
CAM_MINOR_TARGETS[MACRO_INTEGRAZIONE] = [180, 15, 40];
CAM_MINOR_TARGETS[MACRO_AFRICA] = [150, 8, -130];
CAM_MINOR_TARGETS[MACRO_INCLUSIONE] = [-100, 14, -170];
CAM_MINOR_TARGETS[MACRO_COMUNITA] = [0, 0, -1];
export { CAM_MINOR_TARGETS };
//#endregion

//#region CAM SIDE TARGETS
const CAM_SIDE_TARGETS = new Array(6);
CAM_SIDE_TARGETS[MACRO_HOME] = [31, 24, 190];
CAM_SIDE_TARGETS[MACRO_COOPERATIVA] = [-210, 15, 20];
CAM_SIDE_TARGETS[MACRO_INTEGRAZIONE] = [155, 12, 40];
CAM_SIDE_TARGETS[MACRO_AFRICA] = [95, 17, -130];
CAM_SIDE_TARGETS[MACRO_INCLUSIONE] = [-125, 13, -170];
CAM_SIDE_TARGETS[MACRO_COMUNITA] = [-150, 0, -1];
export { CAM_SIDE_TARGETS };
//#endregion

//#region CAM MINOR SIDE TARGETS
const CAM_MINOR_SIDE_TARGETS = new Array(6);
CAM_MINOR_SIDE_TARGETS[MACRO_HOME] = [36, 25, 200];
CAM_MINOR_SIDE_TARGETS[MACRO_COOPERATIVA] = [-185, 17, 20];
CAM_MINOR_SIDE_TARGETS[MACRO_INTEGRAZIONE] = [167, 15, 40];
CAM_MINOR_SIDE_TARGETS[MACRO_AFRICA] = [115, 17, -130];
CAM_MINOR_SIDE_TARGETS[MACRO_INCLUSIONE] = [-120, 14, -170];
CAM_MINOR_SIDE_TARGETS[MACRO_COMUNITA] = [-105, 0, -11];
export { CAM_MINOR_SIDE_TARGETS };
//#endregion

//#region CAM POSITIONS
const CAM_POSITIONS = new Array(6);
CAM_POSITIONS[MACRO_HOME] = [50, 15, 250];
CAM_POSITIONS[MACRO_COOPERATIVA] = [-200, 10, 120];
CAM_POSITIONS[MACRO_INTEGRAZIONE] = [150, 20, 80];
CAM_POSITIONS[MACRO_AFRICA] = [145, 22, -25];
CAM_POSITIONS[MACRO_INCLUSIONE] = [-150, 10, -140];
CAM_POSITIONS[MACRO_COMUNITA] = [0, 300, 0];
export { CAM_POSITIONS };
//#endregion

//#region CAM MINOR POSITIONS
const CAM_MINOR_POSITIONS = new Array(6);
CAM_MINOR_POSITIONS[MACRO_HOME] = [50, 15, 250];
CAM_MINOR_POSITIONS[MACRO_COOPERATIVA] = [-200, 10, 120];
CAM_MINOR_POSITIONS[MACRO_INTEGRAZIONE] = [150, 20, 80];
CAM_MINOR_POSITIONS[MACRO_AFRICA] = [145, 22, -25];
CAM_MINOR_POSITIONS[MACRO_INCLUSIONE] = [-150, 10, -140];
CAM_MINOR_POSITIONS[MACRO_COMUNITA] = [0, 300, 0];
export { CAM_MINOR_POSITIONS };
//#endregion

//#region CAM SIDE POSITIONS
const CAM_SIDE_POSITIONS = new Array(6);
CAM_SIDE_POSITIONS[MACRO_HOME] = [41, 20, 233];
CAM_SIDE_POSITIONS[MACRO_COOPERATIVA] = [-170, 40, 160];
CAM_SIDE_POSITIONS[MACRO_INTEGRAZIONE] = [160, 20, 93];
CAM_SIDE_POSITIONS[MACRO_AFRICA] = [150, 20, 5];
CAM_SIDE_POSITIONS[MACRO_INCLUSIONE] = [-140, 10, -150];
CAM_SIDE_POSITIONS[MACRO_COMUNITA] = [-150, 300, 0];
export { CAM_SIDE_POSITIONS };
//#endregion

//#region CAM MINOR SIDE POSITIONS
const CAM_MINOR_SIDE_POSITIONS = new Array(6);
CAM_MINOR_SIDE_POSITIONS[MACRO_HOME] = [40, 25, 240];
CAM_MINOR_SIDE_POSITIONS[MACRO_COOPERATIVA] = [-145, 35, 140];
CAM_MINOR_SIDE_POSITIONS[MACRO_INTEGRAZIONE] = [160, 20, 80];
CAM_MINOR_SIDE_POSITIONS[MACRO_AFRICA] = [185, 28, -20];
CAM_MINOR_SIDE_POSITIONS[MACRO_INCLUSIONE] = [-140, 10, -150];
CAM_MINOR_SIDE_POSITIONS[MACRO_COMUNITA] = [-105, 350, -10];
export { CAM_MINOR_SIDE_POSITIONS };
//#endregion